### ISSUE TITLE
Overflow of text in mobile view 

### ISSUE THREAD

**Issue by shivaylamba** [yashg160/yashg160.github.io#1]
Hi @yashg160, you have made quite an impressive portfolio site. It is simple and compact. 
There is one issue that should be fixed and it is related to the mobile view of the website. In the mobile view the email address in the about section overflows from the grid. So you should change the text size so that it fits according to the screen size. 
![image](https://user-images.githubusercontent.com/19529592/73195004-1cd47c80-4153-11ea-95d1-95a8fb9a8661.png)

**Comment by yashg160** [comment]
Thanks for informing me. I missed that in the testing. I will fix it today.

**Comment by yashg160** [comment]
![Screenshot](https://user-images.githubusercontent.com/37833972/73256531-180dd800-41e8-11ea-81b5-47f31a76ab4e.png)
I fixed this by simply making the p tag use 12 cols on mobile screen. I think it suits the screen even better.
